# Generated by Django 6.0.4 on 2026-05-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workspace.recurso',),
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workspace.recurso',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workspace.recurso',),
        ),
        migrations.CreateModel(
            name='Projetor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workspace.recurso',),
        ),
        migrations.CreateModel(
            name='Televisao',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workspace.recurso',),
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='nome',
        ),
        migrations.AddField(
            model_name='recurso',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='especificacoes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recurso',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recurso',
            name='modelo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recurso',
            name='numero_serie',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='motivo_manutencao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='prazo_estimado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='tem_computadores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='tem_impressora',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='tem_projetor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='tem_televisao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='tem_videoconferencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('MONITOR', 'Monitor'), ('COMPUTADOR', 'Computador'), ('PROJETOR', 'Projetor'), ('TELEVISAO', 'Televisão'), ('IMPRESSORA', 'Impressora')], max_length=20),
        ),
    ]
