# Generated by Django 6.0.4 on 2026-05-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_computador_impressora_monitor_projetor_televisao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='numero_serie',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
