# Generated by Django 6.0.4 on 2026-05-22 17:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_recurso_marca_alter_recurso_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('tipos_recurso_necessarios', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MONITOR', 'Monitor'), ('COMPUTADOR', 'Computador'), ('PROJETOR', 'Projetor'), ('TELEVISAO', 'Televisão'), ('IMPRESSORA', 'Impressora')], max_length=20), blank=True, default=list)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil_profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='workspace.perfilprofissional'),
        ),
    ]
