# Generated by Django 6.0.4 on 2026-06-12 02:35
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_postodetrabalho_tem_maquina_postodetrabalho_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postodetrabalho',
            name='tipo',
            field=models.CharField(choices=[('INDIVIDUAL', 'Posto Individual'), ('REUNIAO', 'Sala de Reuniao'), ('COLABORATIVO', 'Espaco Colaborativo')], default='INDIVIDUAL', max_length=20),
        ),
    ]