# Generated by Django 6.0.4 on 2026-06-13 00:00

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_alter_postodetrabalho_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postodetrabalho',
            name='tipo',
            field=models.CharField(choices=[('INDIVIDUAL', 'Posto Individual'), ('REUNIAO', 'Sala de Reuni├úo'), ('COLABORATIVO', 'Espa├ºo Colaborativo')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracaoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_funcionamento', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Segunda'), (1, 'Ter├ºa'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'S├íbado'), (6, 'Domingo')]), default=list, help_text='Dias da semana em que a sala funciona (0=Segunda, 6=Domingo)')),
                ('hora_abertura', models.TimeField(default='08:00')),
                ('hora_fechamento', models.TimeField(default='18:00')),
                ('antecedencia_minima_minutos', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('feriados', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list)),
                ('sala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='workspace.sala')),
            ],
        ),
    ]