# Generated by Django 6.0.4 on 2026-06-19 18:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_alter_configuracaosala_dias_funcionamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosala',
            name='dias_funcionamento',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Segunda'), (1, 'Ter├ºa'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'S├íbado'), (6, 'Domingo')]), default=list, help_text='Dias da semana em que a sala funciona (0=Segunda, 6=Domingo)'),
        ),
        migrations.AlterField(
            model_name='postodetrabalho',
            name='tipo',
            field=models.CharField(choices=[('INDIVIDUAL', 'Posto Individual'), ('REUNIAO', 'Sala de Reuni├úo'), ('COLABORATIVO', 'Espa├ºo Colaborativo')], default='INDIVIDUAL', max_length=20),
        ),
    ]