# Generated by Django 6.0.4 on 2026-06-19 22:37

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_alter_configuracaosala_dias_funcionamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosala',
            name='dias_funcionamento',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')]), default=list, help_text='Dias da semana em que a sala funciona (0=Segunda, 6=Domingo)'),
        ),
        migrations.AlterField(
            model_name='postodetrabalho',
            name='tipo',
            field=models.CharField(choices=[('INDIVIDUAL', 'Posto Individual'), ('REUNIAO', 'Sala de Reunião'), ('COLABORATIVO', 'Espaço Colaborativo')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sala',
            name='capacidade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sala',
            name='motivo_manutencao',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
